### ISSUE TITLE
Displays EPVTotal, and not PVEnergyTotal

### ISSUE THREAD

**Issue by mriksman** [muppet3000/homeassistant-grott#8] opened 2023-05-20 06:14 UTC
Hi,

`epvtotal`, `epv1today`, `epv1total`, `epv2today` and `epv2total` is the power generated on the DC (or PV) side. 
`pvenergytoday` and `pvenergytotal` is on the AC side. 

```
-  pvenergytoday        :  17.8
-  pvenergytotal        :  104.9
-  epvtotal             :  106.5
-  epv1today            :  9.9
-  epv1total            :  56.0
-  epv2today            :  8.1
-  epv2total            :  50.5
```
The difference between DC and AC will be the inverter efficiency (98% based on the `epvtotal` and `pvenergytotal`.

In Home Assistant, the value for `pvenergytotal` is missing. Instead, it is displaying `epvtotal`. When determining how much Solar was produced and _consumed_, you need to use the AC converted energy `pvenergytotal`.

Are you able to add `pvenergytotal` to Home Assistant?

![image](https://github.com/muppet3000/homeassistant-grott/assets/20112339/759fa1b2-63ef-4e18-9249-7d6da9d436ca)

**Comment by hajkenek** [comment] 2023-05-29 09:25
I opened the same issue (didn't saw yours). The same problem in my grott instance. I have `pvenergytotal` and it is not equal to `epvtotal` and `pvenergytoday` is equal to `self-consumption` (strange name)
So we need to wait for op.
If you want to add them manually for now, check last screenshot on my issue #11

**Comment by muppet3000** [comment] 2023-06-07 20:29
Hi Both,

Thank you for your contributions to this ticket. Sorry for the delayed response, I've been on holiday.

@hajkenek  - Are you happy for me to close #11 as a duplicate of this one?

@mriksman - Thank you for your explanation of the difference between the AC and DC conversion, that explains the difficulties I was having when I was performing all of the mappings into Home Assistant!!!

Am I correct in saying that what is missing is `pvenergytotal` and that is the same as `pvenergytoday` but it's the all-time total instead of just today's total?

I will map it to `Self-Consumption (Solar + Battery) Energy - Total (pvenergytotal)`. 
To explain the `Self-Consumption` name: This is because this value is what your house consumes from the PV & Battery output during the day, it isn't the total PV generation + Battery usage because it excludes any PV energy that is exported to the grid. Therefore it is the energy that you have generated/stored that you have then consumed.

The difference between the sums is as @mriksman has explained - one is the values in AC, the other is in DC. I should update these names to reflect this in the future, do you agree they should change as follows:

- `Self-Consumption (Solar + Battery) Energy - Today (eactoday)` -> `Self-Consumption (Solar + Battery) Energy - Today (DC)`
- `Self-Consumption (Solar + Battery) Energy - Today (pvenergytoday)` -> `Self-Consumption (Solar + Battery) Energy - Today (AC)`
- `Self-Consumption (Solar + Battery) Energy - Total (eactotal)` -> `Self-Consumption (Solar + Battery) Energy - Total (DC)`
- `Self-Consumption (Solar + Battery) Energy - Total (pvenergytotal)` -> `Self-Consumption (Solar + Battery) Energy - Total (AC)`

**Comment by muppet3000** [comment] 2023-06-07 21:01
This functionality is now available on the `main` branch for testing (you can select this in the re-download menu in HACS)

**Comment by mriksman** [comment] 2023-06-11 03:53
@muppet3000 - I don't have battery, so I can't comment; but what makes you think this is 'consumed' and includes battery? These values feel like they are just related to the power generation on the input side (from the PV) and on the output side (the AC side - what you _actually_ get)

Looking at the web GUI vs the values in Grott/HA
![image](https://github.com/muppet3000/homeassistant-grott/assets/20112339/14653ab6-d629-496f-8cf3-7ae158c08962)
![image](https://github.com/muppet3000/homeassistant-grott/assets/20112339/b004f7fc-d5b5-448d-a3d0-5eb6e044ac63)
I can't find any reference to `epvtotal` on the web GUI.

Looking at the API document (https://growatt.pl/wp-content/uploads/2020/01/Growatt-Server-Open-API-protocol-standards.pdf), I would imagine `powerTotal` is the power generated _after_ the inverter (the AC side). `epvTotal` would be the power generated on the DC side (the PV solar array). I don't think `epvtotal` is important, unless you want to calculate the efficiency.

My option would be to label them simply as
`Total Power Generation (Input PV) - epvtotal` (I don't think there is an `epvtoday`?)
`Total Power Generation - pvenergytotal` (according to the API this is `powertotal`)
`Today Power Generation - pvenergytoday` (according to the API this is `powertoday`)

**Comment by muppet3000** [comment] 2023-06-20 19:47
Hi @mriksman - Sorry, I missed this last week, I'll read through and confirm the values as you've suggested.

Can you at least confirm for me that the new values I added are displaying correctly (if you ignore the names)?

**Comment by mriksman** [comment] 2023-06-21 03:27
Yes; values are good.

**Comment by muppet3000** [comment] 2023-06-21 07:15
Awesome, that's a good start.

I'll take a more detailed look at the naming at some point this week.

**Comment by muppet3000** [comment] 2023-06-22 21:13
I've been looking at this this evening and I agree that I've completely messed up the naming here.

What's odd is that my `epvtotal` which is the AC value is higher than my `eactotal`:
```
- epvtotal: 13183.7
- eactotal: 16598.1

- pvenergytoday: 30.9
- eactoday: 30.9

- epvall (calculated): 30.4 - This is what I see on the WebUI under 'Solar' for today

- pvenergytotal: <not available on my system>
```

Based on your suggestions they should be labelled as follows:
`epvtotal` - PV Generated Energy (DC) - Total
`eactotal` - PV Generated Energy (AC) - Total
`pvenergytoday` - PV Generated Energy (DC) - Today
`eactoday` - PV Generated Energy (AC) - Today

`epvall (calculated)` - PV-All Energy - Total (Calculated)
`pvenergytotal` - PV Generated Energy (DC) - Total - **Is this the same as the `epvtotal` value?**

What do you think? What I can't explain is why my values are the opposite way around to what they should be i.e. AC and DC seem to be the opposite way around.....

**Comment by mriksman** [comment] 2023-06-23 02:21
What model have you got? Battery? In the `grott` logs, I show
```
	 - Grott data record length 585
	 - layout   :  T060104X
	 - no matching record layout found, try generic
	 - Record layout used :  T06NNNNX
```
https://github.com/johanmeijer/grott/blob/60b802ecdac130c07730cff7da3bcd50ef4be61c/grottconf.py#L753
What is yours?

There is also an interesting Excel sheet here, but only seems to relate to SPH.
https://github.com/johanmeijer/grott/blob/master/examples/Documentation/Growatt%20Layout%20definitions%20.xlsx
Notice Item 53 is `Eactoday_H` which he has both `eactoday` and `pvenergytoday` listed.
Confirmed they are the same address - https://github.com/johanmeijer/grott/blob/60b802ecdac130c07730cff7da3bcd50ef4be61c/grottconf.py#L821


Perhaps just leave the naming generic - as it come from `grott`? Let the user decide what and how the values are.

```
Total Power Generation - epvtotal
Today Power Generation - epvall
Total Power Generation - pvenergytotal
Today Power Generation - pvenergytoday
Total Power Generation - eactotal
Today Power Generation - eactoday
```

**Comment by muppet3000** [comment] 2023-07-04 19:40
Pushed this change to main now, it will be 'official' in the next release, but if you want to test before then it's good to go.

**Comment by mriksman** [comment] 2023-07-06 05:19
How can I get HA to update its labels..?

**Comment by muppet3000** [comment] 2023-07-06 07:09
You need to go into HACS for the integration and then click "redownload" and then choose 'main' from the dropdown.

**Comment by muppet3000** [comment] 2023-07-06 07:27
Ahhhh, I didn't change the PV ones as I thought they were correct, these are the ones that I changed:
https://github.com/muppet3000/homeassistant-grott/commit/07473c9ee95d7b716dc04f5a2e45da73b323df1d

Can you confirm that those ones have changed as expected?

**Comment by mriksman** [comment] 2023-07-06 07:36
I'm not sure I understand. My screenshot shows that only one has changed `pvenergytotal`. 
The other two should be `Power Generation - Today (pvenergytoday)` and `Power Generation - Total (epvtotal)`

**Comment by muppet3000** [comment] 2023-07-06 08:16
Did you rename them yourself in HA at some point? Some of those names are different to what it has ever been in the code - did you add something like the values in brackets to some of the existing labels? That will have over-written the value from the Integration and taken precedence.

The ones from your screen grab that have not changed are:
- PV-All Power
- PV-All Energy - Total

The one called "PV-All Energy - Today (pvenergytoday)" used to be called "Self-Consumption (Solar + Battery) Energy - Today (pvenergytoday)" and it looks like you may have renamed it.

**Comment by muppet3000** [comment] 2023-07-06 08:24
If you click on the stat and then click the settings icon, you can change the name of the stat e.g.:
![image](https://github.com/muppet3000/homeassistant-grott/assets/10612068/673e0354-eb2f-42fb-bc8b-01c23cc9d87d)

![image](https://github.com/muppet3000/homeassistant-grott/assets/10612068/5636c4bb-d8ac-46d9-adb8-4adda55713ae)

If there's a value in the 'name' field then you can just delete it and hit 'update' and it'll revert back to the default name.

**Comment by mriksman** [comment] 2023-07-06 08:28
Yup
![image](https://github.com/muppet3000/homeassistant-grott/assets/20112339/6efaa833-2915-4d64-b532-ea2af64b1c95)
All good for me now, thanks.

**Comment by muppet3000** [comment] 2023-07-06 09:43
Thank goodness for that, I was really worried it was some really obscure bug in the integration.

Are we in agreement that the names are now as they should be so I could close this in the next release?

**Comment by mriksman** [comment] 2023-07-06 14:21
I'm happy with what I've got for the names.

**Closed** 2023-07-06 21:20 UTC
