### ISSUE TITLE
Two important entities missing

### ISSUE THREAD

**Issue by hajkenek** [muppet3000/homeassistant-grott#11] opened 2023-05-29 07:28 UTC
Hi,
after adding grott I can see a lot of entity, but there is no: `energy today` and `energy total` (for me the most important).
`pv_all_energy_total is not equal` to `energy total`. In my case `pv_all` gives me more kWh than `energy total`.
the same with `pv_today` and `energy_today`
I am not good at explanation things in english, but my screenshots should explain everything :D 

PS. I forgot to add my inverter type. I'm using `MOD 5000 TL3-X ` (it's new to grott (backend addon))

This is all sensors data displayed by grott
![data_grott](https://github.com/muppet3000/homeassistant-grott/assets/66490316/ef4c3d32-e3d0-42b7-97cc-03b1bde8013d)

This is my raw data from grott (backend addon)
```
	 - Grott values retrieved:
		 -  datalogserial        :  XGD5BH62Q7
		 -  pvserial             :  REH3BHU0L7
		 -  pvstatus             :  1
		 -  pvpowerin            :  0.0
		 -  pv1voltage           :  64.0
		 -  pv1current           :  0.0
		 -  pv1watt              :  0.0
		 -  pv2voltage           :  142.0
		 -  pv2current           :  0.0
		 -  pv2watt              :  0.0
		 -  pvpowerout           :  0.0
		 -  pvfrequentie         :  50.0
		 -  pvgridvoltage        :  235.3
		 -  pvgridcurrent        :  0.4
		 -  pvgridpower          :  94.1
		 -  pvgridvoltage2       :  234.2
		 -  pvgridcurrent2       :  0.4
		 -  pvgridpower2         :  93.6
		 -  pvgridvoltage3       :  233.9
		 -  pvgridcurrent3       :  0.4
		 -  pvgridpower3         :  93.5
		 -  Vac_RS               :  406.1
		 -  Vac_ST               :  405.1
		 -  Vac_TR               :  407.0
		 -  pvenergytoday        :  37.6
		 -  pvenergytotal        :  7087.2
		 -  totworktime          :  5330.8
		 -  epv1today            :  19.2
		 -  epv1total            :  3623.6
		 -  epv2today            :  19.8
		 -  epv2total            :  3675.8
		 -  epvtotal             :  7299.4
		 -  pvtemperature        :  61.1
		 -  pvipmtemperature     :  33.8
		 -  pvboottemperature    :  32.3
		 -  uwBatVolt_DSP        :  39.6
		 -  pbusvolt             :  3132
		 -  nbusvolt             :  3123

```

I've added MQTT data by myself:
![correct_data](https://github.com/muppet3000/homeassistant-grott/assets/66490316/4bb85188-605e-487c-b7f0-ebdb2011a9b3)

**Comment by muppet3000** [comment] 2023-06-20 19:48
Closing as a duplicate of https://github.com/muppet3000/homeassistant-grott/issues/8

**Closed by muppet3000** 2023-06-20 19:48 UTC
